Repository CartoDB/carto-react, pull requests merged in 2022-01, with the labels that each got.

#283 Widgets - Export getTable method for TableWidget model
  packages/react-widgets/src/index.d.ts
  packages/react-widgets/src/index.js
Labels: enhancement

#269 Improve styles for MaterialUI - ToggleButton & ToggleButtonGroup components
  CHANGELOG.md
  packages/react-ui/src/theme/carto-theme.js
  packages/react-ui/storybook/stories/common/ToggleButton.stories.js
Labels: material-ui

#270 Improve styles for MaterialUI - CircularProgress component
  CHANGELOG.md
  packages/react-ui/src/theme/carto-theme.js
  packages/react-ui/storybook/stories/common/Progress.stories.js
Labels: material-ui

#274 Improve styles for MaterialUI - Slider component
  CHANGELOG.md
  packages/react-ui/src/theme/carto-theme.js
  packages/react-ui/storybook/stories/common/Slider.stories.js
Labels: material-ui

#275 Improve styles for MaterialUI - Chip component
  CHANGELOG.md
  packages/react-ui/src/theme/carto-theme.js
  packages/react-ui/storybook/stories/common/Chip.stories.js
Labels: material-ui

#272 Improve styles for MaterialUI - Dialog component
  CHANGELOG.md
  packages/react-ui/src/theme/carto-theme.js
  packages/react-ui/storybook/stories/common/Dialog.stories.js
Labels: material-ui

#299 Align legend expand icon with title
  CHANGELOG.md
  packages/react-ui/src/widgets/legend/LegendWrapper.js
Labels: bug

#300 Align legend icon with its label
  CHANGELOG.md
  packages/react-ui/src/widgets/legend/LegendIcon.js
Labels: bug

#295 Use LegendComponent in LegendWidgetUI as JSX component to avoid react errors
  CHANGELOG.md
  packages/react-ui/src/widgets/legend/LegendWidgetUI.js
Labels: bug

#298 Export new CartoTheme type
  CHANGELOG.md
  packages/react-ui/src/index.d.ts
  packages/react-ui/src/theme/carto-theme.d.ts
Labels: chore

#306 Fix Timeseries wrong filtering with time window
  CHANGELOG.md
  packages/react-ui/src/widgets/TimeSeriesWidgetUI/hooks/TimeSeriesContext.js
Labels: widgets
