Repository CartoDB/carto-react, pull requests merged in 2023-02, with the labels that each got.

#592 Add bearer token in headers instead of using query params
  CHANGELOG.md
  packages/react-api/src/api/SQL.js
  packages/react-core/src/utils/requestsUtils.js
Labels: enhancement

#593 Add sortByColumnType param to fix number sorting in TableWidget
  CHANGELOG.md
  packages/react-widgets/src/models/TableModel.js
  packages/react-widgets/src/widgets/TableWidget.js
  packages/react-workers/src/utils/sorting.js
  packages/react-workers/src/workers/features.worker.js
Labels: builder

#603 Fix: overwrite default client in SQL post request
  CHANGELOG.md
  packages/react-api/src/api/SQL.js
Labels: bug
