Repository CartoDB/carto-react, pull requests merged in 2024-01, with the labels that each got.

#813 Alert component: UI fixes
  CHANGELOG.md
  packages/react-ui/src/components/molecules/Alert.d.ts
  packages/react-ui/src/components/molecules/Alert.js
  packages/react-ui/src/theme/sections/components/feedback.js
  packages/react-ui/storybook/assets/dot.svg
  packages/react-ui/storybook/stories/molecules/Alert.stories.js
Labels: design system

#796 SelectField: extend to accept more data structures as children and to fix placeholder
  CHANGELOG.md
  packages/react-ui/src/components/atoms/LabelWithIndicator.js
  packages/react-ui/src/components/atoms/SelectField.d.ts
  packages/react-ui/src/components/atoms/SelectField.js
  packages/react-ui/storybook/stories/atoms/MiltipleSelectField.stories.js
  packages/react-ui/storybook/stories/atoms/SelectField.stories.js
Labels: design system

#817 UploadField component: UI fixes and extract pure UI components
  CHANGELOG.md
  packages/react-ui/src/components/atoms/SelectField.d.ts
  packages/react-ui/src/components/molecules/UploadField/FilesAction.js
  packages/react-ui/src/components/molecules/UploadField/StyledUploadField.js
  packages/react-ui/src/components/molecules/UploadField/UploadField.d.ts
  packages/react-ui/src/components/molecules/UploadField/UploadField.js
  packages/react-ui/src/components/molecules/UploadField/UploadFieldBase.d.ts
  packages/react-ui/src/components/molecules/UploadField/UploadFieldBase.js
  packages/react-ui/src/index.d.ts
  packages/react-ui/src/index.js
  packages/react-ui/src/types.d.ts
  packages/react-ui/storybook/stories/atoms/LabelWithIndicator.stories.js
  packages/react-ui/storybook/stories/molecules/UploadField.stories.js
Labels: design system

#824 ToggleButtonGroup component: Add support for variant and backgroundColor
  CHANGELOG.md
  UPGRADE.md
  packages/react-ui/src/components/atoms/ToggleButtonGroup.d.ts
  packages/react-ui/src/components/atoms/ToggleButtonGroup.js
  packages/react-ui/src/index.d.ts
  packages/react-ui/src/index.js
  packages/react-ui/src/theme/sections/components/buttons.js
  packages/react-ui/storybook/stories/molecules/ToggleButton.stories.js
Labels: design system

#825 TextField component: Add support for readOnly
  CHANGELOG.md
  UPGRADE.md
  packages/react-ui/src/components/atoms/PasswordField.js
  packages/react-ui/src/theme/sections/components/forms.js
  packages/react-ui/storybook/stories/atoms/Text-area.stories.js
  packages/react-ui/storybook/stories/atoms/Text-field.stories.js
Labels: design system

#830 [react-redux, react-widgets] Add 'GeocoderResult' types, add .passive property
  packages/react-redux/src/types.d.ts
  packages/react-widgets/src/widgets/GeocoderWidget.js
Labels: enhancement, builder

#829 [react-redux] Export 'Filter' types
  CHANGELOG.md
  packages/react-redux/src/slices/cartoSlice.d.ts
Labels: enhancement, builder

#831 [react-widgets] Add initialSearchText prop to useGeocoderWidgetController hook
  CHANGELOG.md
  packages/react-widgets/src/hooks/useGeocoderWidgetController.js
Labels: enhancement, builder

#828 New DS core component: Autocomplete
  CHANGELOG.md
  packages/react-ui/src/components/atoms/SelectField.js
  packages/react-ui/src/components/molecules/UploadField/UploadField.js
  packages/react-ui/src/index.d.ts
  packages/react-ui/src/theme/sections/components/dataDisplay.js
  packages/react-ui/src/theme/sections/components/forms.js
  packages/react-ui/src/theme/sections/components/navigation.js
  packages/react-ui/storybook/stories/atoms/SelectField.stories.js
  packages/react-ui/storybook/stories/atoms/Text-area.stories.js
  packages/react-ui/storybook/stories/atoms/Text-field.stories.js
  packages/react-ui/storybook/stories/molecules/Autocomplete.stories.js
  packages/react-ui/storybook/stories/molecules/ToggleButton.stories.js
Labels: design system

#833 [react-widgets][react-redux] Export missing types from v2.3.9
  packages/react-redux/src/index.d.ts
  packages/react-widgets/src/index.d.ts
  packages/react-widgets/src/index.js
Labels: chore, builder
